# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_tool_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tool_Window(object):
    def setupUi(self, Tool_Window):
        Tool_Window.setObjectName("Tool_Window")
        Tool_Window.resize(450, 100)
        Tool_Window.setMinimumSize(QtCore.QSize(450, 100))
        Tool_Window.setMaximumSize(QtCore.QSize(450, 100))
        self.screen_capture_button = QtWidgets.QPushButton(Tool_Window)
        self.screen_capture_button.setGeometry(QtCore.QRect(30, 20, 60, 60))
        self.screen_capture_button.setObjectName("screen_capture_button")

        self.retranslateUi(Tool_Window)
        QtCore.QMetaObject.connectSlotsByName(Tool_Window)

    def retranslateUi(self, Tool_Window):
        _translate = QtCore.QCoreApplication.translate
        Tool_Window.setWindowTitle(_translate("Tool_Window", "screencapture"))
        self.screen_capture_button.setText(_translate("Tool_Window", "截图"))
